# Generated by Django 3.1.1 on 2020-10-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.title'),
        ),
    ]
