# Generated by Django 3.1.1 on 2020-10-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='project_imgs'),
        ),
    ]
