# Generated by Django 3.1.1 on 2020-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, default='plan/no_image.png', upload_to='project_imgs'),
        ),
    ]
