# Generated by Django 3.1.1 on 2020-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20201019_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='col',
            field=models.CharField(blank=True, default='backlog', max_length=32),
        ),
    ]
