# Generated by Django 3.1.1 on 2020-10-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20201019_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='col',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.tag'),
        ),
    ]
