# Generated by Django 3.1.1 on 2020-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_project_est_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='short_description',
            new_name='headline',
        ),
        migrations.AlterField(
            model_name='project',
            name='est_length',
            field=models.DateTimeField(null=True),
        ),
    ]
