# Generated by Django 3.1.1 on 2020-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20201021_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='est_length',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
