# Generated by Django 3.1.1 on 2020-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20201025_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='est_length',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
