# Generated by Django 3.1.1 on 2020-10-27 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0023_project_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='requesting',
            field=models.ManyToManyField(blank=True, related_name='requesting', to=settings.AUTH_USER_MODEL),
        ),
    ]
